version: '3.7'

services:
  server:
    container_name: farm-grocery-server
    command: npm run dev
    volumes:
      - .:/usr/app/server
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
    tty: true
    build: .